import { Inter } from 'next/font/google'

import { Providers } from '@/store/provider'
import { Sidebar } from '@/modules/Sidebar'

import './globals.scss'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'React Yandex Navigator',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='ru'>
      <body className={inter.className} suppressHydrationWarning>
        <Providers>
          <main className='flex'>
            <Sidebar />
            {children}
          </main>
        </Providers>
      </body>
    </html>
  )
}
