import dynamic from 'next/dynamic'
import { Inter } from 'next/font/google'

import { SplashScreen } from '@/components/Splash'
import { Providers } from '@/store/provider'

import './globals.scss'

const inter = Inter({ subsets: ['latin'] })

const Sidebar = dynamic(
  () => import('@/modules/Sidebar').then((module) => module.Sidebar),
  { ssr: false, loading: () => <SplashScreen /> },
)

export const metadata = {
  title: 'React Yandex Navigator',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='ru'>
      <body className={inter.className} suppressHydrationWarning>
        <Providers>
          <main className='flex'>
            <Sidebar />
            {children}
          </main>
        </Providers>
      </body>
    </html>
  )
}
